version: 2
updates:
  - package-ecosystem: "cargo"
    open-pull-requests-limit: 1000
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      tract:
        applies-to: version-updates
        patterns:
          - "@tract*"
  - package-ecosystem: "pip"
    open-pull-requests-limit: 1000
    versioning-strategy: increase
    directory: "/DeepFilterNet/"
    schedule:
      interval: "daily"

#trigger: 5
