version: 2
updates:
  - package-ecosystem: "cargo"
    open-pull-requests-limit: 1000
    directories:
      - "/"
      - "/demo/"
      - "/ladspa/"
      - "/libDF/"
      - "/pyDF-augment/"
      - "/pyDF-data/"
      - "/pyDF/"
    schedule:
      interval: "daily"
    groups:
      tract:
        applies-to: version-updates
        patterns:
          - "@tract*"
  - package-ecosystem: "pip"
    open-pull-requests-limit: 1000
    directory: "/DeepFilterNet/"
    schedule:
      interval: "daily"

#trigger: 2
