name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 18 * * *'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hook: [flake8, black, isort]
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v6
       with:
         python-version: "3.10"
         cache: 'pip'
         cache-dependency-path: |
           **/pyproject.toml
           .pre-commit-config.yaml
     - name: Install pre-commit
       run: pip install pre-commit
     - name: Run pre-commit ${{ matrix.hook }}
       run: pre-commit run ${{ matrix.hook }} --all-files
